influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'
  volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/influxdb/data
    - ${PROJECT_ROOT}/data/influxdb:/var/lib/influxdb
    - ${PROJECT_ROOT}/etc/influxdb.conf:/etc/influxdb/influxdb.conf:ro

telegraf:
  image: telegraf:latest
  container_name: telegraf
  links:
    - influxdb
  volumes:
    - ${PROJECT_ROOT}/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  user: "0"
  links:
    - influxdb
  volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
    - ${PROJECT_ROOT}/data/grafana:/var/lib/grafana
    - ${PROJECT_ROOT}/etc/grafana.ini:/etc/grafana/grafana.ini:ro

mosquitto:
  image: eclipse-mosquitto:latest
  container_name: mosquitto
  ports:
    - "1883:1883"
    - "9001:9001"
  links:
    - influxdb
  volumes:
    - ${PROJECT_ROOT}/etc/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    - ${PROJECT_ROOT}/data/mosquitto:/mosquitto/data
    - ${PROJECT_ROOT}/log/mosquitto:/mosquitto/log

